# Generated by Django 5.1 on 2025-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('llm_model', models.CharField(default='gpt-4o-mini', max_length=255)),
                ('embed_model', models.CharField(default='text-embedding-3-small', max_length=255)),
                ('top_k', models.IntegerField(default=5)),
                ('chunk_size', models.IntegerField(default=800)),
                ('chunk_overlap', models.IntegerField(default=200)),
                ('system_prompt', models.TextField(default='Ты — AI ассистент.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
