# Generated by Django 5.1 on 2025-11-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_assistant_options_alter_assistant_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='openai_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
