# Generated by Django 5.1 on 2025-11-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_assistant_openai_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistant',
            name='chunk_overlap',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='chunk_size',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='embed_model',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='llm_model',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='top_k',
        ),
    ]
