# Generated by Django 5.1 on 2025-11-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_remove_assistant_chunk_overlap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='llm_model',
            field=models.CharField(default='gpt-4o-mini', max_length=255),
        ),
    ]
