# Generated by Django 5.1 on 2025-11-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_assistant_llm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='llm_model',
            field=models.CharField(choices=[('gpt-5', 'gpt-5'), ('gpt-5-mini', 'gpt-5-mini'), ('gpt-5-nano', 'gpt-5-nano'), ('gpt-4.1', 'gpt-4.1'), ('gpt-4.1-mini', 'gpt-4.1-mini'), ('gpt-4.1-nano', 'gpt-4.1-nano'), ('gpt-4o', 'GPT-4o'), ('gpt-4', 'GPT-4')], default='gpt-5-mini', max_length=50),
        ),
    ]
